// GPU Instancer Pro
// Copyright (c) GurBu Technologies

#ifndef GPUI_SHADER_SETTINGS_INCLUDED
#define GPUI_SHADER_SETTINGS_INCLUDED

#if !(SHADER_API_D3D11 || SHADER_API_GLCORE || SHADER_API_XBOXONE || SHADER_API_GAMECORE || SHADER_API_PSSL || SHADER_API_METAL /*|| SHADER_API_VULKAN*/)
    #define GPUI_NO_BUFFER 1
#endif

#endif // GPUI_SHADER_SETTINGS_INCLUDED